### ISSUE TITLE
Page title has got scrollbar

### ISSUE THREAD

**Issue by nanaya** [nginx/nginx.org#89] opened 2024-10-08 11:15 UTC
The `h2` has `overflow-x: scroll` for some reason which makes zero sense. It's even worse on firefox which ends up showing scrollbar for both directions.

Feel free to close if it's intentional.

![](https://s.kohaku.love/2024/10/firefox_2024-10-08_20-15-14.png)

**Comment by lcrilly** [comment] 2024-10-08 11:31
Duplicate of https://github.com/nginx/nginx.org/issues/49

**Closed by lcrilly** 2024-10-08 11:31 UTC
